import { BookOpen, LoaderCircle } from "lucide-react";
import { type FormEvent, useState } from "react";
import { Button } from "../components/ui/button";

type AuthMode = "login" | "register";
export function AuthPage({ mode, onSubmit, onSwitch }: { mode: AuthMode; onSubmit: (input: { name: string; email: string; password: string }) => Promise<void>; onSwitch: () => void }) {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const register = mode === "register";
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setLoading(true); try { await onSubmit({ name, email, password }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to continue"); } finally { setLoading(false); } }
  return <main className="grid min-h-screen lg:grid-cols-2"><section className="hidden bg-zinc-950 p-12 text-zinc-50 lg:flex lg:flex-col"><div className="flex items-center gap-2 text-lg font-semibold"><span className="grid h-7 w-7 place-items-center rounded-md bg-white text-xs text-zinc-950">V</span>VEONIX</div><div className="my-auto max-w-md"><BookOpen size={32} className="mb-6 text-violet-300" /><h1 className="text-4xl font-semibold tracking-tight">A calmer way to learn.</h1><p className="mt-4 text-zinc-400">Turn your material into focused, AI-assisted revision resources.</p></div><p className="text-sm text-zinc-500">Your private academic workspace.</p></section><section className="flex items-center justify-center p-6"><form className="w-full max-w-sm" onSubmit={submit}><div className="mb-8 lg:hidden"><div className="flex items-center gap-2 text-lg font-semibold"><span className="grid h-7 w-7 place-items-center rounded-md bg-zinc-950 text-xs text-white">V</span>VEONIX</div></div><h2 className="text-2xl font-semibold">{register ? "Create your account" : "Welcome back"}</h2><p className="mt-2 text-sm text-zinc-500">{register ? "Start building your study workspace." : "Sign in to continue learning."}</p><div className="mt-7 space-y-4">{register && <label className="block text-sm font-medium">Name<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-1.5 h-10 w-full rounded-md border border-zinc-200 bg-transparent px-3 outline-none focus:ring-2 focus:ring-zinc-900" placeholder="Your name" /></label>}<label className="block text-sm font-medium">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-1.5 h-10 w-full rounded-md border border-zinc-200 bg-transparent px-3 outline-none focus:ring-2 focus:ring-zinc-900" placeholder="you@example.com" /></label><label className="block text-sm font-medium">Password<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-1.5 h-10 w-full rounded-md border border-zinc-200 bg-transparent px-3 outline-none focus:ring-2 focus:ring-zinc-900" placeholder="At least 8 characters" /></label></div>{error && <p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}<Button className="mt-6 w-full" disabled={loading}>{loading && <LoaderCircle className="mr-2 animate-spin" size={16} />}{register ? "Create account" : "Sign in"}</Button><p className="mt-6 text-center text-sm text-zinc-500">{register ? "Already have an account?" : "New to VEONIX?"} <button type="button" onClick={onSwitch} className="font-medium text-zinc-950 underline">{register ? "Sign in" : "Create an account"}</button></p></form></section></main>;
}
